### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by dada513** [scriptex/create-pwa#54]
When i run
```
create-pwa --icon="./icon.png" --launch="./launch.png"
```
I get this error:
```
internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at resolve (path.js:139:9)
    at getAppName (C:\Users\szsob\AppData\Roaming\npm\node_modules\create-pwa\src\index.js:75:14)
    at create (C:\Users\szsob\AppData\Roaming\npm\node_modules\create-pwa\src\index.js:159:15)
    at Object.<anonymous> (C:\Users\szsob\AppData\Roaming\npm\node_modules\create-pwa\src\index.js:191:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
What am i doing wrong? Im executing the command from the readme

**Comment by scriptex** [comment]
Hello, @dada513, can you please let me know on what OS are you experiencing this? Also, what is the version of the package that you're using?

**Comment by dada513** [comment]
Sorry for the delayed response, using Windows 10 and vscode integrated powershell terminal

**Comment by scriptex** [comment]
Please let me know when you try this. I suspect this has something to do with path separator but not sure.

**Comment by scriptex** [comment]
@dada513 can you please let me know if you still experience this issue?

**Comment by dada513** [comment]
Sorry for the late response, works on `Git Bash`, but doesn't on `Command Prompt` or `PowerShell`

**Comment by scriptex** [comment]
Thank you very much for your time, @dada513 . This is out of the scope of the project in my opinion. I have added this information to the [dependencies section of the README](https://github.com/scriptex/create-pwa#dependencies). 
If you think that it should work in the default Command Prompt or PowerShell on Windows, please file a PR. 
Closing this for now.
